services:
  redis:
    image: redis:8.0-M02-alpine3.20
    container_name: redis
    ports:
      - "6379:6379"
    network_mode: host
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: rcabench
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_USER: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    network_mode: host
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "6831:6831/udp"
      - "14268:14268"
      - "16686:16686"
    network_mode: host
    restart: always

  exp:
    build:
      context: ./experiments_controller
    container_name: exp
    environment:
      GOPRIVATE: "github.com/LGU-SE-Internal/chaos-experiment"
      ENV: "prod"
    command: ["/app/exp", "both", "--port", "8081"]
    volumes:
      - /home/nn/.kube/config:/root/.kube/config
      - ./algorithms:/app/algorithms
      - ./experiments:/app/experiments
      - ./reports:/app/reports
      - ./experiments_controller/config.prod.toml:/etc/rcabench/config.prod.toml
      - ./data:/var/lib/rcabench
      - ./output:/app/output
    working_dir: /app
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - mariadb

volumes:
  mariadb_data:
