apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: rcabench
build:
  artifacts:
    - image: rcabench
      context: .
      docker:
        dockerfile: src/Dockerfile
  tagPolicy:
    envTemplate:
      template: latest
deploy:
  helm:
    releases:
      - name: rcabench
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
        namespace: exp
