// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/iam/v1/iam.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IAMService_VerifyToken_FullMethodName             = "/iam.v1.IAMService/VerifyToken"
	IAMService_CheckPermission_FullMethodName         = "/iam.v1.IAMService/CheckPermission"
	IAMService_Login_FullMethodName                   = "/iam.v1.IAMService/Login"
	IAMService_Register_FullMethodName                = "/iam.v1.IAMService/Register"
	IAMService_RefreshToken_FullMethodName            = "/iam.v1.IAMService/RefreshToken"
	IAMService_Logout_FullMethodName                  = "/iam.v1.IAMService/Logout"
	IAMService_ChangePassword_FullMethodName          = "/iam.v1.IAMService/ChangePassword"
	IAMService_GetProfile_FullMethodName              = "/iam.v1.IAMService/GetProfile"
	IAMService_CreateAccessKey_FullMethodName         = "/iam.v1.IAMService/CreateAccessKey"
	IAMService_ListAccessKeys_FullMethodName          = "/iam.v1.IAMService/ListAccessKeys"
	IAMService_GetAccessKey_FullMethodName            = "/iam.v1.IAMService/GetAccessKey"
	IAMService_DeleteAccessKey_FullMethodName         = "/iam.v1.IAMService/DeleteAccessKey"
	IAMService_DisableAccessKey_FullMethodName        = "/iam.v1.IAMService/DisableAccessKey"
	IAMService_EnableAccessKey_FullMethodName         = "/iam.v1.IAMService/EnableAccessKey"
	IAMService_RotateAccessKey_FullMethodName         = "/iam.v1.IAMService/RotateAccessKey"
	IAMService_IsUserTeamAdmin_FullMethodName         = "/iam.v1.IAMService/IsUserTeamAdmin"
	IAMService_IsUserInTeam_FullMethodName            = "/iam.v1.IAMService/IsUserInTeam"
	IAMService_IsTeamPublic_FullMethodName            = "/iam.v1.IAMService/IsTeamPublic"
	IAMService_IsUserProjectAdmin_FullMethodName      = "/iam.v1.IAMService/IsUserProjectAdmin"
	IAMService_IsUserInProject_FullMethodName         = "/iam.v1.IAMService/IsUserInProject"
	IAMService_ExchangeAccessKeyToken_FullMethodName  = "/iam.v1.IAMService/ExchangeAccessKeyToken"
	IAMService_CreateUser_FullMethodName              = "/iam.v1.IAMService/CreateUser"
	IAMService_DeleteUser_FullMethodName              = "/iam.v1.IAMService/DeleteUser"
	IAMService_GetUser_FullMethodName                 = "/iam.v1.IAMService/GetUser"
	IAMService_ListUsers_FullMethodName               = "/iam.v1.IAMService/ListUsers"
	IAMService_UpdateUser_FullMethodName              = "/iam.v1.IAMService/UpdateUser"
	IAMService_AssignUserRole_FullMethodName          = "/iam.v1.IAMService/AssignUserRole"
	IAMService_RemoveUserRole_FullMethodName          = "/iam.v1.IAMService/RemoveUserRole"
	IAMService_AssignUserPermissions_FullMethodName   = "/iam.v1.IAMService/AssignUserPermissions"
	IAMService_RemoveUserPermissions_FullMethodName   = "/iam.v1.IAMService/RemoveUserPermissions"
	IAMService_AssignUserContainer_FullMethodName     = "/iam.v1.IAMService/AssignUserContainer"
	IAMService_RemoveUserContainer_FullMethodName     = "/iam.v1.IAMService/RemoveUserContainer"
	IAMService_AssignUserDataset_FullMethodName       = "/iam.v1.IAMService/AssignUserDataset"
	IAMService_RemoveUserDataset_FullMethodName       = "/iam.v1.IAMService/RemoveUserDataset"
	IAMService_AssignUserProject_FullMethodName       = "/iam.v1.IAMService/AssignUserProject"
	IAMService_RemoveUserProject_FullMethodName       = "/iam.v1.IAMService/RemoveUserProject"
	IAMService_CreateRole_FullMethodName              = "/iam.v1.IAMService/CreateRole"
	IAMService_DeleteRole_FullMethodName              = "/iam.v1.IAMService/DeleteRole"
	IAMService_GetRole_FullMethodName                 = "/iam.v1.IAMService/GetRole"
	IAMService_ListRoles_FullMethodName               = "/iam.v1.IAMService/ListRoles"
	IAMService_UpdateRole_FullMethodName              = "/iam.v1.IAMService/UpdateRole"
	IAMService_AssignRolePermissions_FullMethodName   = "/iam.v1.IAMService/AssignRolePermissions"
	IAMService_RemoveRolePermissions_FullMethodName   = "/iam.v1.IAMService/RemoveRolePermissions"
	IAMService_ListUsersFromRole_FullMethodName       = "/iam.v1.IAMService/ListUsersFromRole"
	IAMService_GetPermission_FullMethodName           = "/iam.v1.IAMService/GetPermission"
	IAMService_ListPermissions_FullMethodName         = "/iam.v1.IAMService/ListPermissions"
	IAMService_ListRolesFromPermission_FullMethodName = "/iam.v1.IAMService/ListRolesFromPermission"
	IAMService_GetResource_FullMethodName             = "/iam.v1.IAMService/GetResource"
	IAMService_ListResources_FullMethodName           = "/iam.v1.IAMService/ListResources"
	IAMService_ListResourcePermissions_FullMethodName = "/iam.v1.IAMService/ListResourcePermissions"
	IAMService_CreateTeam_FullMethodName              = "/iam.v1.IAMService/CreateTeam"
	IAMService_DeleteTeam_FullMethodName              = "/iam.v1.IAMService/DeleteTeam"
	IAMService_GetTeam_FullMethodName                 = "/iam.v1.IAMService/GetTeam"
	IAMService_ListTeams_FullMethodName               = "/iam.v1.IAMService/ListTeams"
	IAMService_UpdateTeam_FullMethodName              = "/iam.v1.IAMService/UpdateTeam"
	IAMService_ListTeamProjects_FullMethodName        = "/iam.v1.IAMService/ListTeamProjects"
	IAMService_AddTeamMember_FullMethodName           = "/iam.v1.IAMService/AddTeamMember"
	IAMService_RemoveTeamMember_FullMethodName        = "/iam.v1.IAMService/RemoveTeamMember"
	IAMService_UpdateTeamMemberRole_FullMethodName    = "/iam.v1.IAMService/UpdateTeamMemberRole"
	IAMService_ListTeamMembers_FullMethodName         = "/iam.v1.IAMService/ListTeamMembers"
)

// IAMServiceClient is the client API for IAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IAMServiceClient interface {
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error)
	Login(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error)
	Register(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error)
	RefreshToken(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ChangePassword(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetProfile(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	CreateAccessKey(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListAccessKeys(ctx context.Context, in *UserQueryRequest, opts ...grpc.CallOption) (*StructResponse, error)
	GetAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	DeleteAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DisableAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EnableAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RotateAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	IsUserTeamAdmin(ctx context.Context, in *UserTeamRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	IsUserInTeam(ctx context.Context, in *UserTeamRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	IsTeamPublic(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	IsUserProjectAdmin(ctx context.Context, in *UserProjectRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	IsUserInProject(ctx context.Context, in *UserProjectRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	ExchangeAccessKeyToken(ctx context.Context, in *ExchangeAccessKeyTokenRequest, opts ...grpc.CallOption) (*ExchangeAccessKeyTokenResponse, error)
	CreateUser(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error)
	DeleteUser(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUser(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListUsers(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error)
	UpdateUser(ctx context.Context, in *UpdateByIDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	AssignUserRole(ctx context.Context, in *UserRoleBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveUserRole(ctx context.Context, in *UserRoleBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AssignUserPermissions(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveUserPermissions(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AssignUserContainer(ctx context.Context, in *UserResourceBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveUserContainer(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AssignUserDataset(ctx context.Context, in *UserResourceBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveUserDataset(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AssignUserProject(ctx context.Context, in *UserResourceBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveUserProject(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateRole(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error)
	DeleteRole(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetRole(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListRoles(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error)
	UpdateRole(ctx context.Context, in *UpdateByIDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	AssignRolePermissions(ctx context.Context, in *RolePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveRolePermissions(ctx context.Context, in *RolePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListUsersFromRole(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	GetPermission(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListPermissions(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListRolesFromPermission(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	GetResource(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListResources(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListResourcePermissions(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error)
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*StructResponse, error)
	DeleteTeam(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetTeam(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListTeams(ctx context.Context, in *ListTeamsRequest, opts ...grpc.CallOption) (*StructResponse, error)
	UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*StructResponse, error)
	ListTeamProjects(ctx context.Context, in *ListTeamProjectsRequest, opts ...grpc.CallOption) (*StructResponse, error)
	AddTeamMember(ctx context.Context, in *AddTeamMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveTeamMember(ctx context.Context, in *RemoveTeamMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateTeamMemberRole(ctx context.Context, in *UpdateTeamMemberRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTeamMembers(ctx context.Context, in *ListTeamMembersRequest, opts ...grpc.CallOption) (*StructResponse, error)
}

type iAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIAMServiceClient(cc grpc.ClientConnInterface) IAMServiceClient {
	return &iAMServiceClient{cc}
}

func (c *iAMServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, IAMService_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResponse)
	err := c.cc.Invoke(ctx, IAMService_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) Login(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) Register(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RefreshToken(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ChangePassword(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetProfile(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) CreateAccessKey(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_CreateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListAccessKeys(ctx context.Context, in *UserQueryRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListAccessKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_GetAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) DeleteAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_DeleteAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) DisableAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_DisableAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) EnableAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_EnableAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RotateAccessKey(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_RotateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) IsUserTeamAdmin(ctx context.Context, in *UserTeamRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, IAMService_IsUserTeamAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) IsUserInTeam(ctx context.Context, in *UserTeamRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, IAMService_IsUserInTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) IsTeamPublic(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, IAMService_IsTeamPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) IsUserProjectAdmin(ctx context.Context, in *UserProjectRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, IAMService_IsUserProjectAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) IsUserInProject(ctx context.Context, in *UserProjectRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, IAMService_IsUserInProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ExchangeAccessKeyToken(ctx context.Context, in *ExchangeAccessKeyTokenRequest, opts ...grpc.CallOption) (*ExchangeAccessKeyTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeAccessKeyTokenResponse)
	err := c.cc.Invoke(ctx, IAMService_ExchangeAccessKeyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) CreateUser(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) DeleteUser(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetUser(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListUsers(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) UpdateUser(ctx context.Context, in *UpdateByIDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) AssignUserRole(ctx context.Context, in *UserRoleBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_AssignUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RemoveUserRole(ctx context.Context, in *UserRoleBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_RemoveUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) AssignUserPermissions(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_AssignUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RemoveUserPermissions(ctx context.Context, in *UserBodyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_RemoveUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) AssignUserContainer(ctx context.Context, in *UserResourceBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_AssignUserContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RemoveUserContainer(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_RemoveUserContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) AssignUserDataset(ctx context.Context, in *UserResourceBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_AssignUserDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RemoveUserDataset(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_RemoveUserDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) AssignUserProject(ctx context.Context, in *UserResourceBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_AssignUserProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RemoveUserProject(ctx context.Context, in *UserScopedIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_RemoveUserProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) CreateRole(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) DeleteRole(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetRole(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_GetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListRoles(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) UpdateRole(ctx context.Context, in *UpdateByIDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) AssignRolePermissions(ctx context.Context, in *RolePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_AssignRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RemoveRolePermissions(ctx context.Context, in *RolePermissionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_RemoveRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListUsersFromRole(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListUsersFromRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetPermission(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_GetPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListPermissions(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListRolesFromPermission(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListRolesFromPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetResource(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListResources(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListResourcePermissions(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListResourcePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) DeleteTeam(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_DeleteTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) GetTeam(ctx context.Context, in *TeamRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_GetTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListTeams(ctx context.Context, in *ListTeamsRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListTeams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_UpdateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListTeamProjects(ctx context.Context, in *ListTeamProjectsRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListTeamProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) AddTeamMember(ctx context.Context, in *AddTeamMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_AddTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) RemoveTeamMember(ctx context.Context, in *RemoveTeamMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_RemoveTeamMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) UpdateTeamMemberRole(ctx context.Context, in *UpdateTeamMemberRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IAMService_UpdateTeamMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) ListTeamMembers(ctx context.Context, in *ListTeamMembersRequest, opts ...grpc.CallOption) (*StructResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructResponse)
	err := c.cc.Invoke(ctx, IAMService_ListTeamMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAMServiceServer is the server API for IAMService service.
// All implementations must embed UnimplementedIAMServiceServer
// for forward compatibility.
type IAMServiceServer interface {
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error)
	Login(context.Context, *MutationRequest) (*StructResponse, error)
	Register(context.Context, *MutationRequest) (*StructResponse, error)
	RefreshToken(context.Context, *MutationRequest) (*StructResponse, error)
	Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error)
	ChangePassword(context.Context, *UserBodyRequest) (*emptypb.Empty, error)
	GetProfile(context.Context, *UserIDRequest) (*StructResponse, error)
	CreateAccessKey(context.Context, *UserBodyRequest) (*StructResponse, error)
	ListAccessKeys(context.Context, *UserQueryRequest) (*StructResponse, error)
	GetAccessKey(context.Context, *UserScopedIDRequest) (*StructResponse, error)
	DeleteAccessKey(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error)
	DisableAccessKey(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error)
	EnableAccessKey(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error)
	RotateAccessKey(context.Context, *UserScopedIDRequest) (*StructResponse, error)
	IsUserTeamAdmin(context.Context, *UserTeamRequest) (*BoolResponse, error)
	IsUserInTeam(context.Context, *UserTeamRequest) (*BoolResponse, error)
	IsTeamPublic(context.Context, *TeamRequest) (*BoolResponse, error)
	IsUserProjectAdmin(context.Context, *UserProjectRequest) (*BoolResponse, error)
	IsUserInProject(context.Context, *UserProjectRequest) (*BoolResponse, error)
	ExchangeAccessKeyToken(context.Context, *ExchangeAccessKeyTokenRequest) (*ExchangeAccessKeyTokenResponse, error)
	CreateUser(context.Context, *MutationRequest) (*StructResponse, error)
	DeleteUser(context.Context, *IDRequest) (*emptypb.Empty, error)
	GetUser(context.Context, *IDRequest) (*StructResponse, error)
	ListUsers(context.Context, *QueryRequest) (*StructResponse, error)
	UpdateUser(context.Context, *UpdateByIDRequest) (*StructResponse, error)
	AssignUserRole(context.Context, *UserRoleBindingRequest) (*emptypb.Empty, error)
	RemoveUserRole(context.Context, *UserRoleBindingRequest) (*emptypb.Empty, error)
	AssignUserPermissions(context.Context, *UserBodyRequest) (*emptypb.Empty, error)
	RemoveUserPermissions(context.Context, *UserBodyRequest) (*emptypb.Empty, error)
	AssignUserContainer(context.Context, *UserResourceBindingRequest) (*emptypb.Empty, error)
	RemoveUserContainer(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error)
	AssignUserDataset(context.Context, *UserResourceBindingRequest) (*emptypb.Empty, error)
	RemoveUserDataset(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error)
	AssignUserProject(context.Context, *UserResourceBindingRequest) (*emptypb.Empty, error)
	RemoveUserProject(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error)
	CreateRole(context.Context, *MutationRequest) (*StructResponse, error)
	DeleteRole(context.Context, *IDRequest) (*emptypb.Empty, error)
	GetRole(context.Context, *IDRequest) (*StructResponse, error)
	ListRoles(context.Context, *QueryRequest) (*StructResponse, error)
	UpdateRole(context.Context, *UpdateByIDRequest) (*StructResponse, error)
	AssignRolePermissions(context.Context, *RolePermissionsRequest) (*emptypb.Empty, error)
	RemoveRolePermissions(context.Context, *RolePermissionsRequest) (*emptypb.Empty, error)
	ListUsersFromRole(context.Context, *IDRequest) (*StructResponse, error)
	GetPermission(context.Context, *IDRequest) (*StructResponse, error)
	ListPermissions(context.Context, *QueryRequest) (*StructResponse, error)
	ListRolesFromPermission(context.Context, *IDRequest) (*StructResponse, error)
	GetResource(context.Context, *IDRequest) (*StructResponse, error)
	ListResources(context.Context, *QueryRequest) (*StructResponse, error)
	ListResourcePermissions(context.Context, *IDRequest) (*StructResponse, error)
	CreateTeam(context.Context, *CreateTeamRequest) (*StructResponse, error)
	DeleteTeam(context.Context, *TeamRequest) (*emptypb.Empty, error)
	GetTeam(context.Context, *TeamRequest) (*StructResponse, error)
	ListTeams(context.Context, *ListTeamsRequest) (*StructResponse, error)
	UpdateTeam(context.Context, *UpdateTeamRequest) (*StructResponse, error)
	ListTeamProjects(context.Context, *ListTeamProjectsRequest) (*StructResponse, error)
	AddTeamMember(context.Context, *AddTeamMemberRequest) (*emptypb.Empty, error)
	RemoveTeamMember(context.Context, *RemoveTeamMemberRequest) (*emptypb.Empty, error)
	UpdateTeamMemberRole(context.Context, *UpdateTeamMemberRoleRequest) (*emptypb.Empty, error)
	ListTeamMembers(context.Context, *ListTeamMembersRequest) (*StructResponse, error)
	mustEmbedUnimplementedIAMServiceServer()
}

// UnimplementedIAMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAMServiceServer struct{}

func (UnimplementedIAMServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedIAMServiceServer) CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedIAMServiceServer) Login(context.Context, *MutationRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIAMServiceServer) Register(context.Context, *MutationRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedIAMServiceServer) RefreshToken(context.Context, *MutationRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedIAMServiceServer) Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedIAMServiceServer) ChangePassword(context.Context, *UserBodyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedIAMServiceServer) GetProfile(context.Context, *UserIDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedIAMServiceServer) CreateAccessKey(context.Context, *UserBodyRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccessKey not implemented")
}
func (UnimplementedIAMServiceServer) ListAccessKeys(context.Context, *UserQueryRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccessKeys not implemented")
}
func (UnimplementedIAMServiceServer) GetAccessKey(context.Context, *UserScopedIDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccessKey not implemented")
}
func (UnimplementedIAMServiceServer) DeleteAccessKey(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAccessKey not implemented")
}
func (UnimplementedIAMServiceServer) DisableAccessKey(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableAccessKey not implemented")
}
func (UnimplementedIAMServiceServer) EnableAccessKey(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableAccessKey not implemented")
}
func (UnimplementedIAMServiceServer) RotateAccessKey(context.Context, *UserScopedIDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateAccessKey not implemented")
}
func (UnimplementedIAMServiceServer) IsUserTeamAdmin(context.Context, *UserTeamRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsUserTeamAdmin not implemented")
}
func (UnimplementedIAMServiceServer) IsUserInTeam(context.Context, *UserTeamRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsUserInTeam not implemented")
}
func (UnimplementedIAMServiceServer) IsTeamPublic(context.Context, *TeamRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsTeamPublic not implemented")
}
func (UnimplementedIAMServiceServer) IsUserProjectAdmin(context.Context, *UserProjectRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsUserProjectAdmin not implemented")
}
func (UnimplementedIAMServiceServer) IsUserInProject(context.Context, *UserProjectRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsUserInProject not implemented")
}
func (UnimplementedIAMServiceServer) ExchangeAccessKeyToken(context.Context, *ExchangeAccessKeyTokenRequest) (*ExchangeAccessKeyTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeAccessKeyToken not implemented")
}
func (UnimplementedIAMServiceServer) CreateUser(context.Context, *MutationRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedIAMServiceServer) DeleteUser(context.Context, *IDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedIAMServiceServer) GetUser(context.Context, *IDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedIAMServiceServer) ListUsers(context.Context, *QueryRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedIAMServiceServer) UpdateUser(context.Context, *UpdateByIDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedIAMServiceServer) AssignUserRole(context.Context, *UserRoleBindingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserRole not implemented")
}
func (UnimplementedIAMServiceServer) RemoveUserRole(context.Context, *UserRoleBindingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserRole not implemented")
}
func (UnimplementedIAMServiceServer) AssignUserPermissions(context.Context, *UserBodyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserPermissions not implemented")
}
func (UnimplementedIAMServiceServer) RemoveUserPermissions(context.Context, *UserBodyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserPermissions not implemented")
}
func (UnimplementedIAMServiceServer) AssignUserContainer(context.Context, *UserResourceBindingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserContainer not implemented")
}
func (UnimplementedIAMServiceServer) RemoveUserContainer(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserContainer not implemented")
}
func (UnimplementedIAMServiceServer) AssignUserDataset(context.Context, *UserResourceBindingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserDataset not implemented")
}
func (UnimplementedIAMServiceServer) RemoveUserDataset(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserDataset not implemented")
}
func (UnimplementedIAMServiceServer) AssignUserProject(context.Context, *UserResourceBindingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserProject not implemented")
}
func (UnimplementedIAMServiceServer) RemoveUserProject(context.Context, *UserScopedIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserProject not implemented")
}
func (UnimplementedIAMServiceServer) CreateRole(context.Context, *MutationRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedIAMServiceServer) DeleteRole(context.Context, *IDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedIAMServiceServer) GetRole(context.Context, *IDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedIAMServiceServer) ListRoles(context.Context, *QueryRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedIAMServiceServer) UpdateRole(context.Context, *UpdateByIDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedIAMServiceServer) AssignRolePermissions(context.Context, *RolePermissionsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRolePermissions not implemented")
}
func (UnimplementedIAMServiceServer) RemoveRolePermissions(context.Context, *RolePermissionsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRolePermissions not implemented")
}
func (UnimplementedIAMServiceServer) ListUsersFromRole(context.Context, *IDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsersFromRole not implemented")
}
func (UnimplementedIAMServiceServer) GetPermission(context.Context, *IDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermission not implemented")
}
func (UnimplementedIAMServiceServer) ListPermissions(context.Context, *QueryRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedIAMServiceServer) ListRolesFromPermission(context.Context, *IDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRolesFromPermission not implemented")
}
func (UnimplementedIAMServiceServer) GetResource(context.Context, *IDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedIAMServiceServer) ListResources(context.Context, *QueryRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedIAMServiceServer) ListResourcePermissions(context.Context, *IDRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResourcePermissions not implemented")
}
func (UnimplementedIAMServiceServer) CreateTeam(context.Context, *CreateTeamRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedIAMServiceServer) DeleteTeam(context.Context, *TeamRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (UnimplementedIAMServiceServer) GetTeam(context.Context, *TeamRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeam not implemented")
}
func (UnimplementedIAMServiceServer) ListTeams(context.Context, *ListTeamsRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeams not implemented")
}
func (UnimplementedIAMServiceServer) UpdateTeam(context.Context, *UpdateTeamRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (UnimplementedIAMServiceServer) ListTeamProjects(context.Context, *ListTeamProjectsRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeamProjects not implemented")
}
func (UnimplementedIAMServiceServer) AddTeamMember(context.Context, *AddTeamMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTeamMember not implemented")
}
func (UnimplementedIAMServiceServer) RemoveTeamMember(context.Context, *RemoveTeamMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTeamMember not implemented")
}
func (UnimplementedIAMServiceServer) UpdateTeamMemberRole(context.Context, *UpdateTeamMemberRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTeamMemberRole not implemented")
}
func (UnimplementedIAMServiceServer) ListTeamMembers(context.Context, *ListTeamMembersRequest) (*StructResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeamMembers not implemented")
}
func (UnimplementedIAMServiceServer) mustEmbedUnimplementedIAMServiceServer() {}
func (UnimplementedIAMServiceServer) testEmbeddedByValue()                    {}

// UnsafeIAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAMServiceServer will
// result in compilation errors.
type UnsafeIAMServiceServer interface {
	mustEmbedUnimplementedIAMServiceServer()
}

func RegisterIAMServiceServer(s grpc.ServiceRegistrar, srv IAMServiceServer) {
	// If the following call panics, it indicates UnimplementedIAMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAMService_ServiceDesc, srv)
}

func _IAMService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).CheckPermission(ctx, req.(*CheckPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).Login(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).Register(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RefreshToken(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ChangePassword(ctx, req.(*UserBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetProfile(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_CreateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).CreateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_CreateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).CreateAccessKey(ctx, req.(*UserBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListAccessKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListAccessKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListAccessKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListAccessKeys(ctx, req.(*UserQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetAccessKey(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_DeleteAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).DeleteAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_DeleteAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).DeleteAccessKey(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_DisableAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).DisableAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_DisableAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).DisableAccessKey(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_EnableAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).EnableAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_EnableAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).EnableAccessKey(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RotateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RotateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RotateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RotateAccessKey(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_IsUserTeamAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).IsUserTeamAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_IsUserTeamAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).IsUserTeamAdmin(ctx, req.(*UserTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_IsUserInTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).IsUserInTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_IsUserInTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).IsUserInTeam(ctx, req.(*UserTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_IsTeamPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).IsTeamPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_IsTeamPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).IsTeamPublic(ctx, req.(*TeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_IsUserProjectAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).IsUserProjectAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_IsUserProjectAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).IsUserProjectAdmin(ctx, req.(*UserProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_IsUserInProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).IsUserInProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_IsUserInProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).IsUserInProject(ctx, req.(*UserProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ExchangeAccessKeyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeAccessKeyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ExchangeAccessKeyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ExchangeAccessKeyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ExchangeAccessKeyToken(ctx, req.(*ExchangeAccessKeyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).CreateUser(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).DeleteUser(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetUser(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListUsers(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).UpdateUser(ctx, req.(*UpdateByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_AssignUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).AssignUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_AssignUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).AssignUserRole(ctx, req.(*UserRoleBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RemoveUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RemoveUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RemoveUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RemoveUserRole(ctx, req.(*UserRoleBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_AssignUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).AssignUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_AssignUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).AssignUserPermissions(ctx, req.(*UserBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RemoveUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBodyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RemoveUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RemoveUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RemoveUserPermissions(ctx, req.(*UserBodyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_AssignUserContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResourceBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).AssignUserContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_AssignUserContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).AssignUserContainer(ctx, req.(*UserResourceBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RemoveUserContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RemoveUserContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RemoveUserContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RemoveUserContainer(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_AssignUserDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResourceBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).AssignUserDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_AssignUserDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).AssignUserDataset(ctx, req.(*UserResourceBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RemoveUserDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RemoveUserDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RemoveUserDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RemoveUserDataset(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_AssignUserProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResourceBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).AssignUserProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_AssignUserProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).AssignUserProject(ctx, req.(*UserResourceBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RemoveUserProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserScopedIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RemoveUserProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RemoveUserProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RemoveUserProject(ctx, req.(*UserScopedIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).CreateRole(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).DeleteRole(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetRole(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListRoles(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).UpdateRole(ctx, req.(*UpdateByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_AssignRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).AssignRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_AssignRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).AssignRolePermissions(ctx, req.(*RolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RemoveRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RemoveRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RemoveRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RemoveRolePermissions(ctx, req.(*RolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListUsersFromRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListUsersFromRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListUsersFromRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListUsersFromRole(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetPermission(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListPermissions(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListRolesFromPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListRolesFromPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListRolesFromPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListRolesFromPermission(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetResource(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListResources(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListResourcePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListResourcePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListResourcePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListResourcePermissions(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_DeleteTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).DeleteTeam(ctx, req.(*TeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_GetTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetTeam(ctx, req.(*TeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListTeams(ctx, req.(*ListTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_UpdateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).UpdateTeam(ctx, req.(*UpdateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListTeamProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListTeamProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListTeamProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListTeamProjects(ctx, req.(*ListTeamProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_AddTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).AddTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_AddTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).AddTeamMember(ctx, req.(*AddTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_RemoveTeamMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTeamMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).RemoveTeamMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_RemoveTeamMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).RemoveTeamMember(ctx, req.(*RemoveTeamMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_UpdateTeamMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).UpdateTeamMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_UpdateTeamMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).UpdateTeamMemberRole(ctx, req.(*UpdateTeamMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_ListTeamMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).ListTeamMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_ListTeamMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).ListTeamMembers(ctx, req.(*ListTeamMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IAMService_ServiceDesc is the grpc.ServiceDesc for IAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.v1.IAMService",
	HandlerType: (*IAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _IAMService_VerifyToken_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _IAMService_CheckPermission_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _IAMService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _IAMService_Register_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _IAMService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _IAMService_Logout_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _IAMService_ChangePassword_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _IAMService_GetProfile_Handler,
		},
		{
			MethodName: "CreateAccessKey",
			Handler:    _IAMService_CreateAccessKey_Handler,
		},
		{
			MethodName: "ListAccessKeys",
			Handler:    _IAMService_ListAccessKeys_Handler,
		},
		{
			MethodName: "GetAccessKey",
			Handler:    _IAMService_GetAccessKey_Handler,
		},
		{
			MethodName: "DeleteAccessKey",
			Handler:    _IAMService_DeleteAccessKey_Handler,
		},
		{
			MethodName: "DisableAccessKey",
			Handler:    _IAMService_DisableAccessKey_Handler,
		},
		{
			MethodName: "EnableAccessKey",
			Handler:    _IAMService_EnableAccessKey_Handler,
		},
		{
			MethodName: "RotateAccessKey",
			Handler:    _IAMService_RotateAccessKey_Handler,
		},
		{
			MethodName: "IsUserTeamAdmin",
			Handler:    _IAMService_IsUserTeamAdmin_Handler,
		},
		{
			MethodName: "IsUserInTeam",
			Handler:    _IAMService_IsUserInTeam_Handler,
		},
		{
			MethodName: "IsTeamPublic",
			Handler:    _IAMService_IsTeamPublic_Handler,
		},
		{
			MethodName: "IsUserProjectAdmin",
			Handler:    _IAMService_IsUserProjectAdmin_Handler,
		},
		{
			MethodName: "IsUserInProject",
			Handler:    _IAMService_IsUserInProject_Handler,
		},
		{
			MethodName: "ExchangeAccessKeyToken",
			Handler:    _IAMService_ExchangeAccessKeyToken_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _IAMService_CreateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _IAMService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _IAMService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _IAMService_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _IAMService_UpdateUser_Handler,
		},
		{
			MethodName: "AssignUserRole",
			Handler:    _IAMService_AssignUserRole_Handler,
		},
		{
			MethodName: "RemoveUserRole",
			Handler:    _IAMService_RemoveUserRole_Handler,
		},
		{
			MethodName: "AssignUserPermissions",
			Handler:    _IAMService_AssignUserPermissions_Handler,
		},
		{
			MethodName: "RemoveUserPermissions",
			Handler:    _IAMService_RemoveUserPermissions_Handler,
		},
		{
			MethodName: "AssignUserContainer",
			Handler:    _IAMService_AssignUserContainer_Handler,
		},
		{
			MethodName: "RemoveUserContainer",
			Handler:    _IAMService_RemoveUserContainer_Handler,
		},
		{
			MethodName: "AssignUserDataset",
			Handler:    _IAMService_AssignUserDataset_Handler,
		},
		{
			MethodName: "RemoveUserDataset",
			Handler:    _IAMService_RemoveUserDataset_Handler,
		},
		{
			MethodName: "AssignUserProject",
			Handler:    _IAMService_AssignUserProject_Handler,
		},
		{
			MethodName: "RemoveUserProject",
			Handler:    _IAMService_RemoveUserProject_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _IAMService_CreateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _IAMService_DeleteRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _IAMService_GetRole_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _IAMService_ListRoles_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _IAMService_UpdateRole_Handler,
		},
		{
			MethodName: "AssignRolePermissions",
			Handler:    _IAMService_AssignRolePermissions_Handler,
		},
		{
			MethodName: "RemoveRolePermissions",
			Handler:    _IAMService_RemoveRolePermissions_Handler,
		},
		{
			MethodName: "ListUsersFromRole",
			Handler:    _IAMService_ListUsersFromRole_Handler,
		},
		{
			MethodName: "GetPermission",
			Handler:    _IAMService_GetPermission_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _IAMService_ListPermissions_Handler,
		},
		{
			MethodName: "ListRolesFromPermission",
			Handler:    _IAMService_ListRolesFromPermission_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _IAMService_GetResource_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _IAMService_ListResources_Handler,
		},
		{
			MethodName: "ListResourcePermissions",
			Handler:    _IAMService_ListResourcePermissions_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _IAMService_CreateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _IAMService_DeleteTeam_Handler,
		},
		{
			MethodName: "GetTeam",
			Handler:    _IAMService_GetTeam_Handler,
		},
		{
			MethodName: "ListTeams",
			Handler:    _IAMService_ListTeams_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _IAMService_UpdateTeam_Handler,
		},
		{
			MethodName: "ListTeamProjects",
			Handler:    _IAMService_ListTeamProjects_Handler,
		},
		{
			MethodName: "AddTeamMember",
			Handler:    _IAMService_AddTeamMember_Handler,
		},
		{
			MethodName: "RemoveTeamMember",
			Handler:    _IAMService_RemoveTeamMember_Handler,
		},
		{
			MethodName: "UpdateTeamMemberRole",
			Handler:    _IAMService_UpdateTeamMemberRole_Handler,
		},
		{
			MethodName: "ListTeamMembers",
			Handler:    _IAMService_ListTeamMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/iam/v1/iam.proto",
}
