apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-hostpath-init
  namespace: {{ .Values.configmap.k8s.namespace }}
  labels:
    app: {{ .Release.Name }}-hostpath-init
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-hostpath-init
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-hostpath-init
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: init
        image: "{{ .Values.images.busybox.repository }}:{{ .Values.images.busybox.tag }}"
        imagePullPolicy: {{ .Values.images.busybox.pullPolicy }}
        command:
        - sh
        - -c
        - |
          echo "[$(date)] Starting HostPath initialization on node: $(hostname)"
          echo "[$(date)] Creating directories..."
          mkdir -p /host/mnt/jfs/rcabench_dataset
          mkdir -p /host/mnt/jfs/experiment_storage
          mkdir -p /host/var/lib/rcabench
          echo "[$(date)] Setting permissions..."
          chmod 777 /host/mnt/jfs/rcabench_dataset
          chmod 777 /host/mnt/jfs/experiment_storage
          chmod 777 /host/var/lib/rcabench
          echo "[$(date)] Verifying directories..."
          ls -ld /host/mnt/jfs/rcabench_dataset /host/mnt/jfs/experiment_storage /host/var/lib/rcabench
          echo "[$(date)] HostPath directories initialized successfully"
          echo "[$(date)] Keeping container alive for monitoring..."
          while true; do
            sleep 3600
          done
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory