name: "Prepare Command Tool"
description: "Downloads a previously built artifact or executes a local fallback build to ensure the command tool is ready for use."
inputs:
  github-token:
    description: "GitHub token for API access and Artifact downloads."
    required: true
outputs:
  binary_exists:
    description: "Indicates whether the command tool binary was successfully prepared."
    value: ${{ steps.check_binary.outputs.binary_exists }}
runs:
  using: "composite"
  steps:
    - name: Set up variables
      id: setup_vars
      shell: bash
      run: |
        COMMAND_TOOL="scripts/command/command.bin"

        echo "workflow_file=build-make-command.yaml" >> $GITHUB_OUTPUT
        echo "artifact_name=make-command-tool" >> $GITHUB_OUTPUT
        echo "artifact_path=$(dirname ${COMMAND_TOOL})" >> $GITHUB_OUTPUT
        echo "command_tool=${COMMAND_TOOL}" >> $GITHUB_OUTPUT

    - name: ðŸ” Find Latest Successful Build Run
      id: find_run
      uses: ./.github/actions/find-latest-success-run
      with:
        github-token: ${{ inputs.github-token }}
        workflow-file: ${{ steps.setup_vars.outputs.workflow_file }}

    - name: â¬‡ï¸ Download Command Tool artifact
      id: download_artifact
      uses: actions/download-artifact@v4
      if: steps.find_run.outputs.run_id != ''
      with:
        github-token: ${{ inputs.github-token }}
        name: ${{ steps.setup_vars.outputs.artifact_name }}
        path: ${{ steps.setup_vars.outputs.artifact_path }}
        run-id: ${{ steps.find_run.outputs.run_id }}
      continue-on-error: true

    - name: Check if binary exists and set permissions
      id: check_binary
      shell: bash
      run: |
        GREEN="\033[1;32m"
        YELLOW="\033[1;33m"
        RESET="\033[0m"

        command_tool="${{ steps.setup_vars.outputs.command_tool }}"
        if [ -f "${command_tool}" ]; then
          chmod +x "${command_tool}"
          printf "${GREEN}âœ… Binary found and permissions set${RESET}\n"
          ls -lh "${command_tool}"
          echo "binary_exists=true" >> $GITHUB_OUTPUT
        else
          printf "${YELLOW}âš ï¸ Binary not found at ${command_tool}${RESET}\n"
          echo "binary_exists=false" >> $GITHUB_OUTPUT
        fi
