-- ========================================
-- Note: This file has been replaced by automatic initialization in Go code
-- ========================================
-- 
-- The system now automatically performs the following initialization operations at startup:
-- 1. Create system resources and permissions
-- 2. Create system roles (super_admin, admin, project_admin, developer, viewer)
-- 3. Assign appropriate permissions to roles
-- 4. Create super administrator user
-- 5. Create default projects
-- 6. Add super administrator to projects
-- 
-- Initial super administrator account information:
-- Username: admin
-- Email: admin@rcabench.local
-- Password: admin123
-- Full Name: System Administrator
-- 
-- Default projects created:
-- 1. Default Project - System default project for initialization and testing
-- 2. Demo Project - Demonstration project for showcasing system features
-- 
-- If manual initialization is needed (usually not required),
-- you can use the following SQL scripts, but the automatic initialization
-- feature in Go code is recommended.
-- ========================================