apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shared-pv
spec:
  capacity:
    storage: 1024Gi  
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: /mnt/data/rcabench_dataset
    server: 10.26.1.146  
  mountOptions:
    - vers=4  
  storageClassName: nfs-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1024Gi 
  storageClassName: nfs-storage-class