apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared-pvc
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1024Gi 
  storageClassName: nfs-storage-class