apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: container1
      image: debian:latest  
      command: ["sleep", "1000"] 
      volumeMounts:
        - name: shared-volume
          mountPath: /app
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: nfs-shared-pvc 
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: container2
      image: debian:latest  
      command: ["sleep", "1000"]  
      volumeMounts:
        - name: shared-volume
          mountPath: /app
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: nfs-shared-pvc  