port = 8082
debug = true

[system]
timezone = "Asia/Shanghai"

[injection]
namespace = ["ts"]
label = "app"

[storage]
path = "./tasks.db"

[database]
clickhouse_host = "10.10.10.58"

[redis]
host = "localhost:6379"

[harbor]
host = "10.10.10.240"
repository = "10.10.10.240/library"
