port = 8080
debug = false

[system]
timezone = "Asia/Shanghai"

[injection]
namespace = ["ts"]
label = "app"

[storage]
path = "/var/lib/rcabench/tasks.db"

[database]
clickhouse_host = "10.10.10.58"

[redis]
host = "localhost:6379"
