port = 8080
debug = false
workspace = "/app"

[system]
timezone = "Asia/Shanghai"

[injection]
namespace = ["ts"]
interval = 10
label = "app"

[storage]
path = "/var/lib/rcabench/tasks.db"

[database]
clickhouse_host = "10.10.10.58"
mysql_user="root"
mysql_password="yourpassword"
mysql_host="mariadb"
mysql_port="3306"
mysql_db="rcabench"


[redis]
host = "redis:6379"

[harbor]
host = "10.10.10.240"
repository = "10.10.10.240/library"
username = "admin"
password = "Harbor12345"

[k8s]
namespace = "experiment"

[nfs]
path = "/var/lib/rcabench"
pvc_name = "nfs-shared-pvc"
