name = "rcabench"
version = "0.1.0"

port = 8082
debug = true
workspace = "/home/nn/workspace/rcabench"

[system]
timezone = "Asia/Shanghai"

[injection]
enable_duplicate = true
namespace_target_map = { ts = 6 }
target_label_key = "app"

[database]
clickhouse_host = "10.10.10.58"
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "localhost"
mysql_port = "3306"
mysql_db = "rcabench"

[jaeger]
endpoint = "localhost:4318"

[redis]
host = "localhost:6379"

[harbor]
host = "10.10.10.240"
repository = "10.10.10.240/library"
username = "admin"
password = "Harbor12345"

[k8s]
namespace = "exp"

[nfs]
path = "/mnt/nfs/rcabench_dataset"
pvc_name = "nfs-shared-pvc"

[algo]
storage_path = "/home/nn/workspace/rcabench/algorithms"

[debugging]
enable = false

[buildkit]
address = "tcp://localhost:1234"