port = 8082
debug = true
workspace = "/home/nn/workspace/rcabench"

[system]
timezone = "Asia/Shanghai"

[injection]
namespace = ["ts"]
interval = 2
label = "app"

[storage]
path = "./tasks.db"

[database]
clickhouse_host = "10.10.10.58"
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "localhost"
mysql_port = "3306"
mysql_db = "rcabench"

[image]
tag = "latest"

[redis]
host = "localhost:6379"

[harbor]
host = "10.10.10.240"
repository = "10.10.10.240/library"
username = "admin"
password = "Harbor12345"

[k8s]
namespace = "experiment"

[nfs]
path = "/mnt/nfs/rcabench_dataset"
pvc_name = "nfs-shared-pvc"

[algo]
storage_path = "/home/nn/workspace/rcabench/algorithms"