name = "rcabench"
version = "0.1.0"

port = 8080
debug = false
workspace = "/app"

[system]
timezone = "Asia/Shanghai"

[injection]
enable_duplicate = true
namespace_prefix = "ts"
target_label_key = "app"
target_namespace_count = 2
ts_image_tag = "637600ea"

[database]
clickhouse_host = "10.10.10.58"
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "mariadb"
mysql_port = "3306"
mysql_db = "rcabench"

[jaeger]
endpoint = "jaeger:4318"

[redis]
host = "redis:6379"

[harbor]
host = "10.10.10.240"
repository = "10.10.10.240/library"
username = "admin"
password = "Harbor12345"

[k8s]
namespace = "experiment"

[nfs]
path = "/var/lib/rcabench"
pvc_name = "nfs-shared-pvc"

[algo]
storage_path = "/app/algorithms"

[debugging]
enable = false