name = "rcabench"
version = "0.1.0"

port = 8082
debug = true
workspace = "/home/nn/workspace/rcabench"

[system]
env_mode = "dev"
timezone = "Asia/Shanghai"

[debugging]
enable = true

[injection]
enable_duplicate = false
target_label_key = "app"

[injection.namespace_config.ts]
count = 6
port = "31%03d"
repo_name = "train-ticket"
repo_url = "https://lgu-se-internal.github.io/train-ticket"

[database]
clickhouse_host = "10.10.10.58"
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "localhost"
mysql_port = "3306"
mysql_db = "rcabench"

[jaeger]
endpoint = "localhost:4318"

[redis]
host = "localhost:6379"

[harbor]
host = "10.10.10.240"
repository = "10.10.10.240/library"
username = "admin"
password = "Harbor12345"

[k8s]
namespace = "exp"

[jfs]
path = "/mnt/jfs/rcabench_dataset"

[algo]
detector = "detector"
storage_path = "/home/nn/workspace/rcabench/algorithms"


[buildkit]
address = "tcp://localhost:1234"
