definitions:
  dto.AlgorithmExecutionPayload:
    properties:
      algorithm:
        type: string
      dataset:
        type: string
      service:
        type: string
      tag:
        type: string
    type: object
  dto.AlgorithmListResp:
    properties:
      algorithms:
        items:
          type: string
        type: array
    type: object
  dto.Conclusion:
    properties:
      level:
        description: 例如 service level
        type: string
      metric:
        description: 例如 topk
        type: string
      rate:
        type: number
    type: object
  dto.DatasetItem:
    properties:
      end_time:
        type: string
      name:
        type: string
      param:
        additionalProperties: {}
        type: object
      start_time:
        type: string
    type: object
  dto.DatasetPayload:
    properties:
      benchmark:
        type: string
      end_time:
        type: string
      name:
        type: string
      pre_duration:
        type: integer
      service:
        type: string
      start_time:
        type: string
    type: object
  dto.DetectorRecord:
    properties:
      P90:
        type: number
      P95:
        type: number
      P99:
        type: number
      avg_duration:
        type: number
      issue:
        type: string
      span_name:
        type: string
      succ_rate:
        type: number
    type: object
  dto.EvaluationItem:
    properties:
      algorithm:
        type: string
      conclusions:
        items:
          $ref: '#/definitions/dto.Conclusion'
        type: array
      executions:
        items:
          $ref: '#/definitions/dto.Execution'
        type: array
    type: object
  dto.EvaluationListResp:
    properties:
      results:
        items:
          $ref: '#/definitions/dto.EvaluationItem'
        type: array
    type: object
  dto.Execution:
    properties:
      dataset:
        $ref: '#/definitions/dto.DatasetItem'
      granularity_records:
        items:
          $ref: '#/definitions/dto.GranularityRecord'
        type: array
    type: object
  dto.ExecutionRecord:
    properties:
      algorithm:
        type: string
      granularity_records:
        items:
          $ref: '#/definitions/dto.GranularityRecord'
        type: array
    type: object
  dto.GenericResponse-any:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 泛型类型的数据
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GenericResponse-dto_AlgorithmListResp:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/dto.AlgorithmListResp'
        description: 泛型类型的数据
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GenericResponse-dto_EvaluationListResp:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/dto.EvaluationListResp'
        description: 泛型类型的数据
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GenericResponse-dto_PaginationResp-dto_DatasetItem:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/dto.PaginationResp-dto_DatasetItem'
        description: 泛型类型的数据
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GenericResponse-dto_PaginationResp-dto_InjectionItem:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/dto.PaginationResp-dto_InjectionItem'
        description: 泛型类型的数据
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GenericResponse-dto_QueryDatasetResp:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/dto.QueryDatasetResp'
        description: 泛型类型的数据
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GenericResponse-dto_SubmitResp:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/dto.SubmitResp'
        description: 泛型类型的数据
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GenericResponse-int:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 泛型类型的数据
        type: integer
      message:
        description: 响应消息
        type: string
      timestamp:
        description: 响应生成时间
        type: integer
    type: object
  dto.GranularityRecord:
    properties:
      confidence:
        type: number
      level:
        type: string
      rank:
        type: integer
      result:
        type: string
    type: object
  dto.InjectionSubmitReq:
    properties:
      benchmark:
        type: string
      interval:
        type: integer
      pre_duration:
        type: integer
      specs:
        items:
          additionalProperties: {}
          type: object
        type: array
    type: object
  dto.PaginationResp-dto_DatasetItem:
    properties:
      total:
        type: integer
    type: object
  dto.PaginationResp-dto_InjectionItem:
    properties:
      total:
        type: integer
    type: object
  dto.QueryDatasetReq:
    properties:
      name:
        maxLength: 64
        type: string
      sort:
        enum:
        - desc
        - asc
        type: string
    required:
    - name
    type: object
  dto.QueryDatasetResp:
    properties:
      detector_result:
        $ref: '#/definitions/dto.DetectorRecord'
      end_time:
        type: string
      execution_results:
        items:
          $ref: '#/definitions/dto.ExecutionRecord'
        type: array
      name:
        type: string
      param:
        additionalProperties: {}
        type: object
      start_time:
        type: string
    type: object
  dto.SubmitResp:
    properties:
      group_id:
        type: string
      traces:
        items:
          $ref: '#/definitions/dto.Trace'
        type: array
    type: object
  dto.Trace:
    properties:
      head_task_id:
        type: string
      trace_id:
        type: string
    type: object
info:
  contact: {}
  title: RCABench
paths:
  /api/v1/algorithms:
    get:
      description: 获取算法列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_AlgorithmListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 获取算法列表
      tags:
      - algorithm
    post:
      description: 执行算法
      parameters:
      - description: 请求体
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.AlgorithmExecutionPayload'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_SubmitResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 执行算法
      tags:
      - algorithm
  /api/v1/algorithms/build:
    post:
      consumes:
      - multipart/form-data
      description: 通过上传文件或指定算法名称来构建算法镜像
      parameters:
      - description: 算法文件 (zip/tar.gz)
        in: formData
        name: file
        type: file
      - description: 算法名称
        in: formData
        name: algo
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_SubmitResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 构建算法镜像
      tags:
      - algorithm
  /api/v1/datasets:
    get:
      description: 获取状态为成功的注入数据集列表（支持分页参数）
      parameters:
      - default: 1
        description: 页码（从1开始）
        in: query
        minimum: 1
        name: page_num
        required: true
        type: integer
      - default: 10
        description: 每页数量
        in: query
        maximum: 20
        minimum: 5
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_PaginationResp-dto_DatasetItem'
        "400":
          description: 参数校验失败
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 分页查询数据集列表
      tags:
      - dataset
    post:
      description: 批量构建数据集
      parameters:
      - description: 请求体
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.DatasetPayload'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_SubmitResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 批量构建数据集
      tags:
      - dataset
  /api/v1/datasets/delete:
    delete:
      description: 删除数据集数据
      parameters:
      - description: 数据集 ID
        in: path
        name: datasetID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponse-int'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 删除数据集数据
      tags:
      - dataset
  /api/v1/datasets/download:
    get:
      description: 将指定路径的多个数据集打包为 ZIP 文件下载（自动排除 result.csv 文件）
      produces:
      - application/zip
      responses:
        "200":
          description: ZIP 文件流
          schema:
            type: string
        "400":
          description: 参数绑定错误
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "403":
          description: 非法路径访问
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: 文件打包失败
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 下载数据集打包文件
      tags:
      - dataset
  /api/v1/evaluations:
    get:
      description: 返回每种算法的执行历史记录
      parameters:
      - collectionFormat: csv
        description: 执行结果 ID 数组
        in: query
        items:
          type: integer
        name: execution_ids
        type: array
      - collectionFormat: csv
        description: 算法名称数组
        in: query
        items:
          type: string
        name: algorithms
        type: array
      - collectionFormat: csv
        description: 级别名称数组
        in: query
        items:
          type: string
        name: levels
        type: array
      - collectionFormat: csv
        description: 指标名称数组
        in: query
        items:
          type: string
        name: metrics
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_EvaluationListResp'
        "400":
          description: 参数校验失败
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 获取每种算法的执行历史记录
      tags:
      - evaluation
  /api/v1/injections:
    post:
      description: 注入故障
      parameters:
      - description: 请求体
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.InjectionSubmitReq'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_SubmitResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 注入故障
      tags:
      - injection
  /api/v1/injections/getlist:
    post:
      description: 获取注入记录列表（支持分页参数）
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GenericResponse-dto_PaginationResp-dto_InjectionItem'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.GenericResponse-any'
      summary: 分页查询注入记录列表
      tags:
      - injection
swagger: "2.0"
