#!/usr/bin/env python3
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

OLD_FUNC_RE = re.compile(r"^func\s+([A-Za-z0-9_]+)\s*\(")
NEW_METHOD_RE = re.compile(r"^func\s+\([^)]*\)\s+([A-Za-z0-9_]+)\s*\(")


@dataclass(frozen=True)
class Mapping:
    source: str
    source_func: str
    target: str
    target_func: str


MAPPINGS = [
    Mapping(
        "src/handlers/v2/access_keys.go",
        "CreateAccessKey",
        "src/module/auth/handler.go",
        "CreateAccessKey",
    ),
    Mapping(
        "src/handlers/v2/access_keys.go",
        "ListAccessKeys",
        "src/module/auth/handler.go",
        "ListAccessKeys",
    ),
    Mapping(
        "src/handlers/v2/access_keys.go",
        "GetAccessKey",
        "src/module/auth/handler.go",
        "GetAccessKey",
    ),
    Mapping(
        "src/handlers/v2/access_keys.go",
        "DeleteAccessKey",
        "src/module/auth/handler.go",
        "DeleteAccessKey",
    ),
    Mapping(
        "src/handlers/v2/access_keys.go",
        "RotateAccessKey",
        "src/module/auth/handler.go",
        "RotateAccessKey",
    ),
    Mapping(
        "src/handlers/v2/access_keys.go",
        "DisableAccessKey",
        "src/module/auth/handler.go",
        "DisableAccessKey",
    ),
    Mapping(
        "src/handlers/v2/access_keys.go",
        "EnableAccessKey",
        "src/module/auth/handler.go",
        "EnableAccessKey",
    ),
    Mapping(
        "src/handlers/v2/access_keys.go",
        "ExchangeAccessKeyToken",
        "src/module/auth/handler.go",
        "ExchangeAccessKeyToken",
    ),
    Mapping(
        "src/handlers/v2/auth.go", "Register", "src/module/auth/handler.go", "Register"
    ),
    Mapping("src/handlers/v2/auth.go", "Login", "src/module/auth/handler.go", "Login"),
    Mapping(
        "src/handlers/v2/auth.go",
        "RefreshToken",
        "src/module/auth/handler.go",
        "RefreshToken",
    ),
    Mapping(
        "src/handlers/v2/auth.go", "Logout", "src/module/auth/handler.go", "Logout"
    ),
    Mapping(
        "src/handlers/v2/auth.go",
        "ChangePassword",
        "src/module/auth/handler.go",
        "ChangePassword",
    ),
    Mapping(
        "src/handlers/v2/auth.go",
        "GetProfile",
        "src/module/auth/handler.go",
        "GetProfile",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "CreateContainer",
        "src/module/container/handler.go",
        "CreateContainer",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "DeleteContainer",
        "src/module/container/handler.go",
        "DeleteContainer",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "GetContainer",
        "src/module/container/handler.go",
        "GetContainer",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "ListContainers",
        "src/module/container/handler.go",
        "ListContainers",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "UpdateContainer",
        "src/module/container/handler.go",
        "UpdateContainer",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "CreateContainerVersion",
        "src/module/container/handler.go",
        "CreateContainerVersion",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "DeleteContainerVersion",
        "src/module/container/handler.go",
        "DeleteContainerVersion",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "GetContainerVersion",
        "src/module/container/handler.go",
        "GetContainerVersion",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "ListContainerVersions",
        "src/module/container/handler.go",
        "ListContainerVersions",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "UpdateContainerVersion",
        "src/module/container/handler.go",
        "UpdateContainerVersion",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "ManageContainerCustomLabels",
        "src/module/container/handler.go",
        "ManageContainerCustomLabels",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "SubmitContainerBuilding",
        "src/module/container/handler.go",
        "SubmitContainerBuilding",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "UploadHelmChart",
        "src/module/container/handler.go",
        "UploadHelmChart",
    ),
    Mapping(
        "src/handlers/v2/containers.go",
        "UploadHelmValueFile",
        "src/module/container/handler.go",
        "UploadHelmValueFile",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "CreateDataset",
        "src/module/dataset/handler.go",
        "CreateDataset",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "DeleteDataset",
        "src/module/dataset/handler.go",
        "DeleteDataset",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "GetDataset",
        "src/module/dataset/handler.go",
        "GetDataset",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "ListDatasets",
        "src/module/dataset/handler.go",
        "ListDatasets",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "SearchDataset",
        "src/module/dataset/handler.go",
        "SearchDataset",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "UpdateDataset",
        "src/module/dataset/handler.go",
        "UpdateDataset",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "ManageDatasetCustomLabels",
        "src/module/dataset/handler.go",
        "ManageDatasetCustomLabels",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "CreateDatasetVersion",
        "src/module/dataset/handler.go",
        "CreateDatasetVersion",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "DeleteDatasetVersion",
        "src/module/dataset/handler.go",
        "DeleteDatasetVersion",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "GetDatasetVersion",
        "src/module/dataset/handler.go",
        "GetDatasetVersion",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "ListDatasetVersions",
        "src/module/dataset/handler.go",
        "ListDatasetVersions",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "UpdateDatasetVersion",
        "src/module/dataset/handler.go",
        "UpdateDatasetVersion",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "DownloadDatasetVersion",
        "src/module/dataset/handler.go",
        "DownloadDatasetVersion",
    ),
    Mapping(
        "src/handlers/v2/datasets.go",
        "ManageDatasetVersionInjections",
        "src/module/dataset/handler.go",
        "ManageDatasetVersionInjections",
    ),
    Mapping(
        "src/handlers/v2/evaluations.go",
        "ListDatapackEvaluationResults",
        "src/module/evaluation/handler.go",
        "ListDatapackEvaluationResults",
    ),
    Mapping(
        "src/handlers/v2/evaluations.go",
        "ListDatasetEvaluationResults",
        "src/module/evaluation/handler.go",
        "ListDatasetEvaluationResults",
    ),
    Mapping(
        "src/handlers/v2/evaluations.go",
        "ListEvaluations",
        "src/module/evaluation/handler.go",
        "ListEvaluations",
    ),
    Mapping(
        "src/handlers/v2/evaluations.go",
        "GetEvaluation",
        "src/module/evaluation/handler.go",
        "GetEvaluation",
    ),
    Mapping(
        "src/handlers/v2/evaluations.go",
        "DeleteEvaluation",
        "src/module/evaluation/handler.go",
        "DeleteEvaluation",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "BatchDeleteExecutions",
        "src/module/execution/handler.go",
        "BatchDeleteExecutions",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "GetExecution",
        "src/module/execution/handler.go",
        "GetExecution",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "ListExecutions",
        "src/module/execution/handler.go",
        "ListExecutions",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "ListAvaliableExecutionLabels",
        "src/module/execution/handler.go",
        "ListAvailableExecutionLabels",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "ManageExecutionCustomLabels",
        "src/module/execution/handler.go",
        "ManageExecutionCustomLabels",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "SubmitAlgorithmExecution",
        "src/module/execution/handler.go",
        "SubmitAlgorithmExecution",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "UploadDetectorResults",
        "src/module/execution/handler.go",
        "UploadDetectorResults",
    ),
    Mapping(
        "src/handlers/v2/executions.go",
        "UploadGranularityResults",
        "src/module/execution/handler.go",
        "UploadGranularityResults",
    ),
    Mapping(
        "src/handlers/v2/groups.go",
        "GetGroupStats",
        "src/module/group/handler.go",
        "GetGroupStats",
    ),
    Mapping(
        "src/handlers/v2/groups.go",
        "GetGroupStream",
        "src/module/group/handler.go",
        "GetGroupStream",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "BatchDeleteInjections",
        "src/module/injection/handler.go",
        "BatchDeleteInjections",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "GetInjection",
        "src/module/injection/handler.go",
        "GetInjection",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "GetInjectionMetadata",
        "src/module/injection/handler.go",
        "GetInjectionMetadata",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "ListInjections",
        "src/module/injection/handler.go",
        "ListInjections",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "SearchInjections",
        "src/module/injection/handler.go",
        "SearchInjections",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "ListFaultInjectionNoIssues",
        "src/module/injection/handler.go",
        "ListFaultInjectionNoIssues",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "ListFaultInjectionWithIssues",
        "src/module/injection/handler.go",
        "ListFaultInjectionWithIssues",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "ManageInjectionCustomLabels",
        "src/module/injection/handler.go",
        "ManageInjectionCustomLabels",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "BatchManageInjectionLabels",
        "src/module/injection/handler.go",
        "BatchManageInjectionLabels",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "SubmitFaultInjection",
        "src/module/injection/handler.go",
        "SubmitFaultInjection",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "SubmitDatapackBuilding",
        "src/module/injection/handler.go",
        "SubmitDatapackBuilding",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "CloneInjection",
        "src/module/injection/handler.go",
        "CloneInjection",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "GetInjectionLogs",
        "src/module/injection/handler.go",
        "GetInjectionLogs",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "DownloadDatapack",
        "src/module/injection/handler.go",
        "DownloadDatapack",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "ListDatapackFiles",
        "src/module/injection/handler.go",
        "ListDatapackFiles",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "DownloadDatapackFile",
        "src/module/injection/handler.go",
        "DownloadDatapackFile",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "QueryDatapackFile",
        "src/module/injection/handler.go",
        "QueryDatapackFile",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "UploadDatapack",
        "src/module/injection/handler.go",
        "UploadDatapack",
    ),
    Mapping(
        "src/handlers/v2/injections.go",
        "UpdateGroundtruth",
        "src/module/injection/handler.go",
        "UpdateGroundtruth",
    ),
    Mapping(
        "src/handlers/v2/labels.go",
        "BatchDeleteLabels",
        "src/module/label/handler.go",
        "BatchDeleteLabels",
    ),
    Mapping(
        "src/handlers/v2/labels.go",
        "CreateLabel",
        "src/module/label/handler.go",
        "CreateLabel",
    ),
    Mapping(
        "src/handlers/v2/labels.go",
        "DeleteLabel",
        "src/module/label/handler.go",
        "DeleteLabel",
    ),
    Mapping(
        "src/handlers/v2/labels.go",
        "GetLabelDetail",
        "src/module/label/handler.go",
        "GetLabelDetail",
    ),
    Mapping(
        "src/handlers/v2/labels.go",
        "ListLabels",
        "src/module/label/handler.go",
        "ListLabels",
    ),
    Mapping(
        "src/handlers/v2/labels.go",
        "UpdateLabel",
        "src/module/label/handler.go",
        "UpdateLabel",
    ),
    Mapping(
        "src/handlers/v2/metrics.go",
        "GetInjectionMetrics",
        "src/module/metric/handler.go",
        "GetInjectionMetrics",
    ),
    Mapping(
        "src/handlers/v2/metrics.go",
        "GetExecutionMetrics",
        "src/module/metric/handler.go",
        "GetExecutionMetrics",
    ),
    Mapping(
        "src/handlers/v2/metrics.go",
        "GetAlgorithmMetrics",
        "src/module/metric/handler.go",
        "GetAlgorithmMetrics",
    ),
    Mapping(
        "src/handlers/v2/notifications.go",
        "GetNotificationStream",
        "src/module/notification/handler.go",
        "GetStream",
    ),
    Mapping(
        "src/handlers/v2/permissions.go",
        "GetPermission",
        "src/module/rbac/handler.go",
        "GetPermission",
    ),
    Mapping(
        "src/handlers/v2/permissions.go",
        "ListPermissions",
        "src/module/rbac/handler.go",
        "ListPermissions",
    ),
    Mapping(
        "src/handlers/v2/permissions.go",
        "ListRolesFromPermission",
        "src/module/rbac/handler.go",
        "ListRolesFromPermission",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "CreateProject",
        "src/module/project/handler.go",
        "CreateProject",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "DeleteProject",
        "src/module/project/handler.go",
        "DeleteProject",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "GetProjectDetail",
        "src/module/project/handler.go",
        "GetProjectDetail",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "ListProjects",
        "src/module/project/handler.go",
        "ListProjects",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "UpdateProject",
        "src/module/project/handler.go",
        "UpdateProject",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "ManageProjectCustomLabels",
        "src/module/project/handler.go",
        "ManageProjectCustomLabels",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "ListProjectInjections",
        "src/module/injection/handler.go",
        "ListProjectInjections",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "SearchProjectInjections",
        "src/module/injection/handler.go",
        "SearchProjectInjections",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "ListProjectFaultInjectionNoIssues",
        "src/module/injection/handler.go",
        "ListProjectFaultInjectionNoIssues",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "ListProjectFaultInjectionWithIssues",
        "src/module/injection/handler.go",
        "ListProjectFaultInjectionWithIssues",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "SubmitProjectFaultInjection",
        "src/module/injection/handler.go",
        "SubmitProjectFaultInjection",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "SubmitProjectDatapackBuilding",
        "src/module/injection/handler.go",
        "SubmitProjectDatapackBuilding",
    ),
    Mapping(
        "src/handlers/v2/projects.go",
        "ListProjectExecutions",
        "src/module/execution/handler.go",
        "ListProjectExecutions",
    ),
    Mapping(
        "src/handlers/v2/resources.go",
        "GetResourceDetail",
        "src/module/rbac/handler.go",
        "GetResource",
    ),
    Mapping(
        "src/handlers/v2/resources.go",
        "ListResources",
        "src/module/rbac/handler.go",
        "ListResources",
    ),
    Mapping(
        "src/handlers/v2/resources.go",
        "ListResourcePermissions",
        "src/module/rbac/handler.go",
        "ListResourcePermissions",
    ),
    Mapping(
        "src/handlers/v2/roles.go",
        "CreateRole",
        "src/module/rbac/handler.go",
        "CreateRole",
    ),
    Mapping(
        "src/handlers/v2/roles.go",
        "DeleteRole",
        "src/module/rbac/handler.go",
        "DeleteRole",
    ),
    Mapping(
        "src/handlers/v2/roles.go", "GetRole", "src/module/rbac/handler.go", "GetRole"
    ),
    Mapping(
        "src/handlers/v2/roles.go",
        "ListRoles",
        "src/module/rbac/handler.go",
        "ListRoles",
    ),
    Mapping(
        "src/handlers/v2/roles.go",
        "UpdateRole",
        "src/module/rbac/handler.go",
        "UpdateRole",
    ),
    Mapping(
        "src/handlers/v2/roles.go",
        "AssignRolePermission",
        "src/module/rbac/handler.go",
        "AssignRolePermissions",
    ),
    Mapping(
        "src/handlers/v2/roles.go",
        "RemovePermissionsFromRole",
        "src/module/rbac/handler.go",
        "RemoveRolePermissions",
    ),
    Mapping(
        "src/handlers/v2/sdk_evaluations.go",
        "ListSDKEvaluations",
        "src/module/sdk/handler.go",
        "ListEvaluations",
    ),
    Mapping(
        "src/handlers/v2/sdk_evaluations.go",
        "GetSDKEvaluation",
        "src/module/sdk/handler.go",
        "GetEvaluation",
    ),
    Mapping(
        "src/handlers/v2/sdk_evaluations.go",
        "ListSDKExperiments",
        "src/module/sdk/handler.go",
        "ListExperiments",
    ),
    Mapping(
        "src/handlers/v2/sdk_evaluations.go",
        "ListSDKDatasetSamples",
        "src/module/sdk/handler.go",
        "ListDatasetSamples",
    ),
    Mapping(
        "src/handlers/v2/system.go",
        "GetSystemMetrics",
        "src/module/systemmetric/handler.go",
        "GetSystemMetrics",
    ),
    Mapping(
        "src/handlers/v2/system.go",
        "GetSystemMetricsHistory",
        "src/module/systemmetric/handler.go",
        "GetSystemMetricsHistory",
    ),
    Mapping(
        "src/handlers/v2/systems.go",
        "ListChaosSystemsHandler",
        "src/module/chaossystem/handler.go",
        "ListSystems",
    ),
    Mapping(
        "src/handlers/v2/systems.go",
        "GetChaosSystemHandler",
        "src/module/chaossystem/handler.go",
        "GetSystem",
    ),
    Mapping(
        "src/handlers/v2/systems.go",
        "CreateChaosSystemHandler",
        "src/module/chaossystem/handler.go",
        "CreateSystem",
    ),
    Mapping(
        "src/handlers/v2/systems.go",
        "UpdateChaosSystemHandler",
        "src/module/chaossystem/handler.go",
        "UpdateSystem",
    ),
    Mapping(
        "src/handlers/v2/systems.go",
        "DeleteChaosSystemHandler",
        "src/module/chaossystem/handler.go",
        "DeleteSystem",
    ),
    Mapping(
        "src/handlers/v2/systems.go",
        "UpsertChaosSystemMetadataHandler",
        "src/module/chaossystem/handler.go",
        "UpsertMetadata",
    ),
    Mapping(
        "src/handlers/v2/systems.go",
        "ListChaosSystemMetadataHandler",
        "src/module/chaossystem/handler.go",
        "ListMetadata",
    ),
    Mapping(
        "src/handlers/v2/tasks.go",
        "BatchDeleteTasks",
        "src/module/task/handler.go",
        "BatchDelete",
    ),
    Mapping("src/handlers/v2/tasks.go", "GetTask", "src/module/task/handler.go", "Get"),
    Mapping(
        "src/handlers/v2/tasks.go", "ListTasks", "src/module/task/handler.go", "List"
    ),
    Mapping(
        "src/handlers/v2/tasks.go",
        "GetTaskLogsWS",
        "src/module/task/handler.go",
        "LogsWS",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "CreateTeam",
        "src/module/team/handler.go",
        "CreateTeam",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "DeleteTeam",
        "src/module/team/handler.go",
        "DeleteTeam",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "GetTeamDetail",
        "src/module/team/handler.go",
        "GetTeamDetail",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "ListTeams",
        "src/module/team/handler.go",
        "ListTeams",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "UpdateTeam",
        "src/module/team/handler.go",
        "UpdateTeam",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "ListTeamProjects",
        "src/module/team/handler.go",
        "ListTeamProjects",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "AddTeamMember",
        "src/module/team/handler.go",
        "AddTeamMember",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "RemoveTeamMember",
        "src/module/team/handler.go",
        "RemoveTeamMember",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "UpdateTeamMemberRole",
        "src/module/team/handler.go",
        "UpdateTeamMemberRole",
    ),
    Mapping(
        "src/handlers/v2/teams.go",
        "ListTeamMembers",
        "src/module/team/handler.go",
        "ListTeamMembers",
    ),
    Mapping(
        "src/handlers/v2/traces.go",
        "GetTrace",
        "src/module/trace/handler.go",
        "GetTrace",
    ),
    Mapping(
        "src/handlers/v2/traces.go",
        "ListTraces",
        "src/module/trace/handler.go",
        "ListTraces",
    ),
    Mapping(
        "src/handlers/v2/traces.go",
        "GetTraceStream",
        "src/module/trace/handler.go",
        "GetTraceStream",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "CreateUser",
        "src/module/user/handler.go",
        "CreateUser",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "DeleteUser",
        "src/module/user/handler.go",
        "DeleteUser",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "GetUserDetailV2",
        "src/module/user/handler.go",
        "GetUserDetail",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "ListUsersV2",
        "src/module/user/handler.go",
        "ListUsers",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "UpdateUser",
        "src/module/user/handler.go",
        "UpdateUser",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "AssignUserRole",
        "src/module/user/handler.go",
        "AssignRole",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "RemoveGlobalRole",
        "src/module/user/handler.go",
        "RemoveRole",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "AssignUserPermission",
        "src/module/user/handler.go",
        "AssignPermissions",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "RemoveUserPermission",
        "src/module/user/handler.go",
        "RemovePermissions",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "AssignUserContainer",
        "src/module/user/handler.go",
        "AssignContainer",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "RemoveUserContainer",
        "src/module/user/handler.go",
        "RemoveContainer",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "AssignUserDataset",
        "src/module/user/handler.go",
        "AssignDataset",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "RemoveUserDataset",
        "src/module/user/handler.go",
        "RemoveDataset",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "AssignUserProject",
        "src/module/user/handler.go",
        "AssignProject",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "RemoveUserProject",
        "src/module/user/handler.go",
        "RemoveProject",
    ),
    Mapping(
        "src/handlers/v2/users.go",
        "ListUsersFromRole",
        "src/module/rbac/handler.go",
        "ListUsersFromRole",
    ),
    Mapping(
        "src/handlers/system/audit.go",
        "GetAuditLog",
        "src/module/system/handler.go",
        "GetAuditLog",
    ),
    Mapping(
        "src/handlers/system/audit.go",
        "ListAuditLogs",
        "src/module/system/handler.go",
        "ListAuditLogs",
    ),
    Mapping(
        "src/handlers/system/configs.go",
        "GetConfig",
        "src/module/system/handler.go",
        "GetConfig",
    ),
    Mapping(
        "src/handlers/system/configs.go",
        "ListConfigs",
        "src/module/system/handler.go",
        "ListConfigs",
    ),
    Mapping(
        "src/handlers/system/configs.go",
        "RollbackConfigValue",
        "src/module/system/handler.go",
        "RollbackConfigValue",
    ),
    Mapping(
        "src/handlers/system/configs.go",
        "RollbackConfigMetadata",
        "src/module/system/handler.go",
        "RollbackConfigMetadata",
    ),
    Mapping(
        "src/handlers/system/configs.go",
        "UpdateConfigValue",
        "src/module/system/handler.go",
        "UpdateConfigValue",
    ),
    Mapping(
        "src/handlers/system/configs.go",
        "UpdateConfigMetadata",
        "src/module/system/handler.go",
        "UpdateConfigMetadata",
    ),
    Mapping(
        "src/handlers/system/configs.go",
        "ListConfigHistories",
        "src/module/system/handler.go",
        "ListConfigHistories",
    ),
    Mapping(
        "src/handlers/system/health.go",
        "GetHealth",
        "src/module/system/handler.go",
        "GetHealth",
    ),
    Mapping(
        "src/handlers/system/monitor.go",
        "GetMetrics",
        "src/module/system/handler.go",
        "GetMetrics",
    ),
    Mapping(
        "src/handlers/system/monitor.go",
        "GetSystemInfo",
        "src/module/system/handler.go",
        "GetSystemInfo",
    ),
    Mapping(
        "src/handlers/system/monitor.go",
        "ListNamespaceLocks",
        "src/module/system/handler.go",
        "ListNamespaceLocks",
    ),
    Mapping(
        "src/handlers/system/monitor.go",
        "ListQueuedTasks",
        "src/module/system/handler.go",
        "ListQueuedTasks",
    ),
]


def read_lines(path: str) -> list[str]:
    return (REPO_ROOT / path).read_text(encoding="utf-8").splitlines()


def extract_comments(path: str) -> dict[str, list[str]]:
    lines = read_lines(path)
    comments: dict[str, list[str]] = {}
    for idx, line in enumerate(lines):
        match = OLD_FUNC_RE.match(line.strip())
        if not match:
            continue
        func_name = match.group(1)
        start = idx - 1
        while start >= 0 and lines[start].startswith("//"):
            start -= 1
        block = lines[start + 1 : idx]
        if block and any("@Router" in item for item in block):
            comments[func_name] = block
    return comments


def inject_comments(path: str, blocks: dict[str, list[str]]) -> None:
    lines = read_lines(path)
    output: list[str] = []
    idx = 0
    while idx < len(lines):
        stripped = lines[idx].strip()
        match = NEW_METHOD_RE.match(stripped)
        if match and match.group(1) in blocks:
            start = len(output)
            while start > 0 and output[start - 1].startswith("//"):
                start -= 1
            if start > 0 and output[start - 1] == "":
                # Preserve a single separator before the comment block.
                pass
            if start < len(output):
                output = output[:start]
                if output and output[-1] != "":
                    output.append("")
            elif output and output[-1] != "":
                output.append("")
            output.extend(blocks[match.group(1)])
        output.append(lines[idx])
        idx += 1
    (REPO_ROOT / path).write_text("\n".join(output) + "\n", encoding="utf-8")


def main() -> None:
    source_cache: dict[str, dict[str, list[str]]] = {}
    target_blocks: dict[str, dict[str, list[str]]] = {}

    for mapping in MAPPINGS:
        if mapping.source not in source_cache:
            source_cache[mapping.source] = extract_comments(mapping.source)
        block = source_cache[mapping.source].get(mapping.source_func)
        if not block:
            raise RuntimeError(
                f"missing comment block for {mapping.source}:{mapping.source_func}"
            )
        target_blocks.setdefault(mapping.target, {})[mapping.target_func] = block

    for target, blocks in target_blocks.items():
        inject_comments(target, blocks)
        print(f"updated {target} ({len(blocks)} methods)")


if __name__ == "__main__":
    main()
