global:
  imageRegistry: 10.10.10.240/library

images:
  rcabench:
    name: rcabench
  jaeger:
    name: jaeger
  buildkit:
    name: buildkit

harbor:
  enabled: true

configmap:
  k8s:
    init_container:
      busybox_image: pair-diag-cn-guangzhou.cr.volces.com/pair/busybox:1.35

