name: Publish Helm Chart

on:
  push:
    paths:
      - 'helm/**'
      - '.github/workflows/release-helm.yml'

jobs:
  call-helm-release:
    uses: OperationsPAI/shared-workflows/.github/workflows/release-helm.yml@main
    with: 
      repo_name: rcabench
      repo_url: https://operationspai.github.io/AegisLab/
      tag_push: ${{ startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit